#!/usr/bin/env bash

#add the chages
git add -A

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
#--> Run git stuf
if [[ $CURRENT_BRANCH == production ]] || [[ $CURRENT_BRANCH == development ]]; then
	echo -e "\e[41m Cannot save to protected branches \e[0m\n"
    exit
fi;

while true; do
    echo -e "\e[45m -----> Check for errors in your commit? \e[0m\n (highly suggested before commiting)";
    read -p  "_____Type 'y'(yes) or 'n'(no)____" yn
    case $yn in
        [Yy]* ) FLAGS=''; ADDMSG=' --VERIFIED'; break;;
        [Nn]* ) FLAGS='--no-verify '; ADDMSG=' --NOT--Verified'; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

#commit the message
if [ -n "$1" ]; then  
    MESSAGE=$*$ADDMSG
else
    MESSAGE="WIP$ADDMSG"
fi;

git commit -am "$MESSAGE" $FLAGS

if [ $? != 0 ]
then
    exit
fi

echo -e "\e[45m saved with message ==> $MESSAGE \e[0m\n"
#complete transaction by pulling and pushing the code
git pull
git push
