#!/usr/bin/env bash

# If nothing then exit
if [ -z "$1" ]; then 
    echo -e "\e[41m No Branch specified \e[0m\n"
    exit
fi;

while true; do
    read -p "--------- Opening a branch, have you saved/stashed your previous changes?" yn
    case $yn in
        [Yy]* ) echo "Installing-> $1"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

#--> Run git stuf
if [[ $CURRENT_BRANCH == production ]] || [[ $CURRENT_BRANCH == development ]]; then
	git checkout -f
fi;



if [ ! -z "$2" ]; then 
    targetBranch=$2
else
    targetBranch='development'
fi;

set -x
git checkout .
git checkout $targetBranch
git reset --hard
git pull origin $targetBranch
git fetch

IS_BRANCH=`git ls-remote --heads origin $1`

if [[ $IS_BRANCH ]]; then
	git checkout $1
   	git pull
else
	git checkout -b $1
	git push -u origin $1
fi;
set +x